# This is the name of the workflow as it will appear in the "Actions" tab
name: Daily Commit Action

on:
  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
  
  # This schedules the workflow to run automatically
  schedule:
    # This uses cron syntax to run at 05:30 UTC every day.
    # It uses specific minutes (30) and hours (05) as required.
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # Grant permissions for the workflow to write to your repository (to push a commit)
    permissions:
      contents: write

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need a token to push the commit
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Configure Git user (this step's name includes the required email)
      - name: Configure Git user for 24f2001048@ds.study.iitm.ac.in
        run: |
          git config --global user.name 'Daily Commit Bot'
          git config --global user.email 'daily-commit-bot@users.noreply.github.com'
          
      # Step 3: Create and push the empty commit
      - name: Create a new commit
        run: |
          git commit --allow-empty -m "Scheduled daily update"
          git push
